#lang sicp
(define point cons)
(define x-coor car)
(define y-coor cdr)
(define (print-point p)
  (newline)
  (display "(")
  (display (x-coor p))
  (display ",")
  (display (y-coor p))
  (display ")")
)
(define segment cons)
(define start car)
(define end cdr)
(define (midpoint p q)
  (point (/ (+ (x-coor p) (x-coor q)) 2) (/ (+ (y-coor p) (y-coor q)) 2)
  )
)  
(define (midpoint-segment s)
  (midpoint (start s) (end s))
)  
  